---
# 1. Archive + user : déjà faits

- name: Créer répertoire /etc/prometheus
  file:
    path: /etc/prometheus
    state: directory
    owner: prometheus
    group: prometheus
    mode: 0755

- name: Copier binaires Prometheus & promtool
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: prometheus
    group: prometheus
    mode: 0755
  loop:
    - { src: "/opt/prometheus-{{ prometheus_version }}.linux-amd64/prometheus", dest: "/usr/local/bin/prometheus" }
    - { src: "/opt/prometheus-{{ prometheus_version }}.linux-amd64/promtool",    dest: "/usr/local/bin/promtool" }

- name: Déployer configuration Prometheus
  template:
    src: prometheus.yml.j2
    dest: /etc/prometheus/prometheus.yml
    owner: prometheus
    group: prometheus
    mode: 0644
  notify: restart prometheus

- name: Service systemd Prometheus
  template:
    src: prometheus.service.j2
    dest: /etc/systemd/system/prometheus.service
    mode: 0644
  notify:
    - daemon reload
    - restart prometheus
